apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: csd9g173e-go
  janus-idp.io/tekton: csd9g173e-go
  backstage.io/kubernetes-id: csd9g173e-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: csd9g173e-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
